# Generated by Django 4.0.5 on 2022-06-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_account', models.CharField(max_length=20, verbose_name='유저 계정')),
                ('password', models.CharField(max_length=40, verbose_name='유저 비밀번호')),
                ('password2', models.CharField(max_length=40, verbose_name='비밀번호 체크')),
                ('user_name', models.CharField(max_length=10, verbose_name='유저 이름')),
                ('nickname', models.CharField(max_length=10, verbose_name='유저 닉네임')),
                ('user_phone', models.CharField(max_length=15, verbose_name='유저 핸드폰 번호')),
                ('user_email', models.EmailField(max_length=30, verbose_name='유저 이메일')),
            ],
        ),
    ]
